#***************************************# 
#         구별 데이터 분리              #      
#***************************************# 
AIR_day <- read.csv('./data/airseoul_day.csv', header = T)[,-1]
AIR_day$SGG <- factor(AIR_day$SGG)
AIR_day$DATE <- as.Date(AIR_day$DATE)

df <- AIR_day[,c(2,1,3:7)]
tr = df[df$DATE < '2020-01-01',]
te = df[df$DATE >= '2020-01-01',]
#***************************************#
kind_ssg <-as.character(unique(AIR_day$SGG));
sgg1 = tr[tr$SGG==kind_ssg[1],]
sgg2 = tr[tr$SGG==kind_ssg[2],]
sgg3 = tr[tr$SGG==kind_ssg[3],]
sgg4 = tr[tr$SGG==kind_ssg[4],]
sgg5 = tr[tr$SGG==kind_ssg[5],]
sgg6 = tr[tr$SGG==kind_ssg[6],]
sgg7 = tr[tr$SGG==kind_ssg[7],]
sgg8 = tr[tr$SGG==kind_ssg[8],]
sgg9 = tr[tr$SGG==kind_ssg[9],]
sgg10 = tr[tr$SGG==kind_ssg[10],]

sgg11 = tr[tr$SGG==kind_ssg[11],]
sgg12 = tr[tr$SGG==kind_ssg[12],]
sgg13 = tr[tr$SGG==kind_ssg[13],]
sgg14 = tr[tr$SGG==kind_ssg[14],]
sgg15 = tr[tr$SGG==kind_ssg[15],]
sgg16 = tr[tr$SGG==kind_ssg[16],]
sgg17 = tr[tr$SGG==kind_ssg[17],]
sgg18 = tr[tr$SGG==kind_ssg[18],]
sgg19 = tr[tr$SGG==kind_ssg[19],]
sgg20 = tr[tr$SGG==kind_ssg[20],]

sgg21 = tr[tr$SGG==kind_ssg[21],]
sgg22 = tr[tr$SGG==kind_ssg[22],]
sgg23 = tr[tr$SGG==kind_ssg[23],]
sgg24 = tr[tr$SGG==kind_ssg[24],]
sgg25 = tr[tr$SGG==kind_ssg[25],]
sgg26 = tr[tr$SGG==kind_ssg[26],]
sgg27 = tr[tr$SGG==kind_ssg[27],]
sgg28 = tr[tr$SGG==kind_ssg[28],]
sgg29 = tr[tr$SGG==kind_ssg[29],]
sgg30 = tr[tr$SGG==kind_ssg[30],]

sgg30 = tr[tr$SGG==kind_ssg[30],]
sgg31 = tr[tr$SGG==kind_ssg[31],]
sgg32 = tr[tr$SGG==kind_ssg[32],]
sgg33 = tr[tr$SGG==kind_ssg[33],]
sgg34 = tr[tr$SGG==kind_ssg[34],]
sgg35 = tr[tr$SGG==kind_ssg[35],]
sgg36 = tr[tr$SGG==kind_ssg[36],]
sgg37 = tr[tr$SGG==kind_ssg[37],]
sgg38 = tr[tr$SGG==kind_ssg[38],]
sgg39 = tr[tr$SGG==kind_ssg[39],]
#***************************************#
sgg1.te = te[te$SGG==kind_ssg[1],]
sgg2.te = te[te$SGG==kind_ssg[2],]
sgg3.te = te[te$SGG==kind_ssg[3],]
sgg4.te = te[te$SGG==kind_ssg[4],]
sgg5.te = te[te$SGG==kind_ssg[5],]
sgg6.te = te[te$SGG==kind_ssg[6],]
sgg7.te = te[te$SGG==kind_ssg[7],]
sgg8.te = te[te$SGG==kind_ssg[8],]
sgg9.te = te[te$SGG==kind_ssg[9],]
sgg10.te = te[te$SGG==kind_ssg[10],]

sgg11 = te[te$SGG==kind_ssg[11],]
sgg12 = te[te$SGG==kind_ssg[12],]
sgg13 = te[te$SGG==kind_ssg[13],]
sgg14 = te[te$SGG==kind_ssg[14],]
sgg15 = te[te$SGG==kind_ssg[15],]
sgg16 = te[te$SGG==kind_ssg[16],]
sgg17 = te[te$SGG==kind_ssg[17],]
sgg18 = te[te$SGG==kind_ssg[18],]
sgg19 = te[te$SGG==kind_ssg[19],]
sgg20 = te[te$SGG==kind_ssg[20],]

sgg21 = te[te$SGG==kind_ssg[21],]
sgg22 = te[te$SGG==kind_ssg[22],]
sgg23 = te[te$SGG==kind_ssg[23],]
sgg24 = te[te$SGG==kind_ssg[24],]
sgg25 = te[te$SGG==kind_ssg[25],]
sgg26 = te[te$SGG==kind_ssg[26],]
sgg27 = te[te$SGG==kind_ssg[27],]
sgg28 = te[te$SGG==kind_ssg[28],]
sgg29 = te[te$SGG==kind_ssg[29],]
sgg30 = te[te$SGG==kind_ssg[30],]

sgg30 = te[te$SGG==kind_ssg[30],]
sgg31 = te[te$SGG==kind_ssg[31],]
sgg32 = te[te$SGG==kind_ssg[32],]
sgg33 = te[te$SGG==kind_ssg[33],]
sgg34 = te[te$SGG==kind_ssg[34],]
sgg35 = te[te$SGG==kind_ssg[35],]
sgg36 = te[te$SGG==kind_ssg[36],]
sgg37 = te[te$SGG==kind_ssg[37],]
sgg38 = te[te$SGG==kind_ssg[38],]
sgg39 = te[te$SGG==kind_ssg[39],]

